# This workflow builds and tests EasyUI on multiple platforms
name: CMake Build

on:
  push:
    branches: [ "main", "test-workflow" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            cmake_generator: "Visual Studio 17 2022"
          - os: ubuntu-latest
            cmake_generator: "Unix Makefiles"
          - os: macos-latest
            cmake_generator: "Unix Makefiles"

    steps:
    - uses: actions/checkout@v3

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        cmake -B build -G "${{ matrix.cmake_generator }}" -DCI_BUILD=ON

    - name: Configure CMake (Unix)
      if: runner.os != 'Windows'
      run: |
        cmake -B build -G "${{ matrix.cmake_generator }}" -DCI_BUILD=ON

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    - name: Test
      working-directory: build
      run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
