# This workflow builds and tests EasyUI on multiple platforms
name: CMake on multiple platforms

on:
  push:
    branches: [ "main", "test-workflow" ]
  pull_request:
    branches: [ "main", "test-workflow" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            c_compiler: cl
            build_type: Release
          - os: ubuntu-latest
            c_compiler: gcc
            build_type: Release
          - os: macos-latest
            c_compiler: clang
            build_type: Release

    steps:
    - uses: actions/checkout@v4

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libx11-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libxi-dev

    - name: Install macOS Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install cmake

    - name: Configure CMake on Windows
      if: runner.os == 'Windows'
      run: |
        cmake -B ${{github.workspace}}/build `
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} `
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
          -DCI_BUILD=ON

    - name: Configure CMake on Unix
      if: runner.os != 'Windows'
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCI_BUILD=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{ matrix.build_type }} --output-on-failure
